# Generated by Django 4.2.3 on 2023-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjobs',
            options={'verbose_name_plural': 'Applied Jobs'},
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='address',
            field=models.TextField(blank=True, default='Kathmandu', max_length=50, null=True, verbose_name='Address'),
        ),
    ]
