# Generated by Django 4.2.3 on 2023-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_appliedjobs_options_jobseeker_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job',
            field=models.TextField(blank=True, null=True, verbose_name='Preference'),
        ),
    ]
