# Generated by Django 4.2.3 on 2023-10-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_jobseeker_preferred_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='preferred_job',
        ),
    ]
