# Generated by Django 4.2.3 on 2023-10-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_remove_jobseeker_preferred_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='experiences',
            field=models.TextField(blank=True, null=True, verbose_name='Experiences'),
        ),
    ]
