# Generated by Django 4.2.3 on 2023-11-07 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_job_location'),
        ('jobseeker', '0008_score_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListedCandidates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseeker')),
            ],
        ),
    ]
