# Generated by Django 4.2.3 on 2023-11-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_shortlistedcandidates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlistedcandidates',
            options={'verbose_name_plural': 'Short Listed Candidates'},
        ),
    ]
