# Generated by Django 4.2.3 on 2023-11-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_alter_shortlistedcandidates_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_shortlisted',
            field=models.BooleanField(default=False, verbose_name='Shortlisted'),
        ),
    ]
