# Generated by Django 4.2.3 on 2023-08-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employer name')),
                ('emp_phone_number', models.CharField(max_length=11, verbose_name='Employer number')),
                ('emp_email', models.EmailField(max_length=254, unique=True, verbose_name='Employer Email')),
                ('emp_password', models.CharField(max_length=25, verbose_name='Employer Password')),
                ('about_employer', models.TextField(blank=True, null=True, verbose_name='About Employer')),
                ('emp_profile', models.FileField(null=True, upload_to='employer-profile/', verbose_name='Profile Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('Full time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance')], max_length=50, verbose_name='Job type')),
                ('job_position', models.CharField(max_length=100, verbose_name='Position')),
                ('job_requirement', models.CharField(max_length=100, verbose_name='Requirements')),
                ('job_description', models.TextField(verbose_name='Description')),
                ('salary', models.TextField(blank=True, max_length=30, null=True)),
                ('location_type', models.TextField(choices=[('Hybrid', 'Hybrid'), ('On Site', 'On Site'), ('Online', 'Online')])),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150, verbose_name='Questions')),
                ('marks', models.CharField(default=5, max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='employer.job')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('is_answer_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='employer.questions')),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
