# Generated by Django 4.2.3 on 2023-10-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
