# Generated by Django 4.2.3 on 2023-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(default='Kathmandu', max_length=40),
        ),
    ]
