# Generated by Django 4.2.3 on 2023-10-05 04:16

from django.db import migrations, models
import employer.utility


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_employer_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=employer.utility.default_deadline),
        ),
    ]
