# Generated by Django 4.2.3 on 2023-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
